[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "C4", "SIM", "E402"] 
ignore = ["F841"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
known-first-party = ["training", "backend"]
force-single-line = false

[tool.black]
line-length = 100
target-version = ['py312']
skip-string-normalization = true